import type { ProfileType } from "./profileTypes";

export const SECTION_TYPES = [
  "hero",
  "about",
  "contact",
  "hours",
  "services",
  "rooms",
  "products",
  "menu",
  "gallery",
  "testimonials",
  "social",
  "location",
  "booking",
  "cta",
  "faq",
  "links",
  "experience",
  "education",
  "certifications",
  "specialization",
  "skills",
  "portfolio",
  "amenities",
  "footer",
] as const;

export type SectionType = (typeof SECTION_TYPES)[number];

export const SECTION_REGISTRY: Record<SectionType, { label: string; description: string }> = {
  hero: { label: "Hero", description: "Cover, logo, name, and introduction." },
  about: { label: "About", description: "Story and description." },
  contact: { label: "Contact", description: "Phone, email, WhatsApp, website." },
  hours: { label: "Opening Hours", description: "Weekly schedule." },
  services: { label: "Services", description: "Hotel or business services." },
  rooms: { label: "Rooms", description: "Hotel rooms and presentation." },
  products: { label: "Products", description: "Simple product highlights." },
  menu: { label: "Menu", description: "Restaurant or cafeteria menu." },
  gallery: { label: "Gallery", description: "Photo gallery." },
  testimonials: { label: "Testimonials", description: "Quotes from guests or clients." },
  social: { label: "Social Media", description: "Public social links." },
  location: { label: "Location", description: "Address and maps." },
  booking: { label: "Booking", description: "Call-to-action for reservations." },
  cta: { label: "Call To Action", description: "A highlighted action block." },
  faq: { label: "FAQ", description: "Common questions." },
  links: { label: "Links", description: "Useful outbound links." },
  experience: { label: "Experience", description: "Work history or highlights." },
  education: { label: "Education", description: "Schools, degrees, and training." },
  certifications: { label: "Certifications", description: "Licenses and certificates." },
  specialization: { label: "Specialization", description: "Area of practice or expertise." },
  skills: { label: "Skills", description: "Skills and specialties." },
  portfolio: { label: "Portfolio", description: "Selected work." },
  amenities: { label: "Amenities", description: "Hotel or venue amenities." },
  footer: { label: "Footer", description: "Closing line." },
};

export const TYPE_SECTION_PRESETS: Record<ProfileType, SectionType[]> = {
  PERSONAL: ["hero", "about", "experience", "skills", "portfolio", "social", "contact", "location", "footer"],
  INDIVIDUAL_BUSINESS: ["hero", "about", "services", "portfolio", "gallery", "social", "location", "contact", "footer"],
  BUSINESS: ["hero", "about", "services", "products", "gallery", "social", "location", "contact", "footer"],
  ORGANIZATION: ["hero", "about", "services", "gallery", "social", "location", "contact", "footer"],
  HOTEL: ["hero", "about", "rooms", "services", "amenities", "gallery", "hours", "location", "booking", "social", "contact", "footer"],
  RESTAURANT: ["hero", "about", "menu", "hours", "gallery", "location", "social", "contact", "footer"],
  CAFETERIA: ["hero", "about", "menu", "hours", "gallery", "location", "social", "contact", "footer"],
  DOCTOR: ["hero", "about", "specialization", "services", "experience", "education", "certifications", "location", "contact", "social", "cta", "footer"],
  ENGINEER: ["hero", "about", "specialization", "experience", "skills", "services", "portfolio", "social", "location", "contact", "footer"],
  PROFESSIONAL: ["hero", "about", "specialization", "experience", "skills", "services", "portfolio", "social", "location", "contact", "footer"],
  PORTFOLIO: ["hero", "about", "portfolio", "gallery", "skills", "social", "location", "contact", "footer"],
};
